/*
NOTE:
This file starts with 1 so it appears at the top of the regression tests folder during development.
We should rename this file without the "1-" before opening a PR for review.
*/

// print single digit number followed by newline; accounts for ascii offset
putd cout_ c =
  after 1, cout_ <- c + 48    // Should print 5
  wait cout_
  after 1, cout_ <- 10
  wait cout_

/*
Example:  r is oncesafe, q is multiunsafe; post-inline inlines q
Input:
main cin cout = 
  let q = 2
  let r = 3 + q
  putd cout (r + q - q)

Expected Output:
main cin cout = 
  let q = 2
  let r = 3 + q
  putd cout (3 + 2 + 2 -2)
  
*/

main cin cout = 
  let q = 2
  let r = 3 + q
  putd cout (r + q - q)

  