/*
NOTE:
This file starts with 1 so it appears at the top of the regression tests folder during development.
We should rename this file without the "1-" before opening a PR for review.

  stack build
  cd regression-tests
  ./runtests.sh -k tests/1-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-lifted tests/1-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-inlined tests/1-inlining-ex-1.ssl
  stack exec sslc -- tests/1-inlining-ex-1.ssl

CORRECT OUTPUT
  UnexpectedError (ErrorMsg "\"
  [\\\"START topdef VarId main has OccInfo: \\\\\\\"fromList 
  [(VarId cin,Dead),
  (VarId cout,Dead),
  (VarId q,OnceSafe),
  (VarId r,OnceSafe),
  (VarId y,Dead)]\\\\\\\" END\\\",

  \\\"START topdef VarId f has OccInfo: \\\\\\\"fromList [
    (VarId cin,Dead),
    (VarId cout,Dead),
    (VarId q,OnceSafe),
    (VarId r,OnceSafe),
    (VarId y,OnceSafe)]\\\\\\\" END\\\"]\"")

*/

/* 
Example: r and q are oncesafe.
Input:
main = 
  let q = 5
  IN
  let r = q + 1 
  IN 
  r

Expected Output:
main = 
  5 + 1

*/

// print single digit; account for ascii offset
putd cout_ c =
  after 1, cout_ <- (c + 48)
  wait cout_

main cin cout = 
  let q = 5
  let r = q + 1 
  putd cout r
