/*
NOTE:
This file starts with 1 so it appears at the top of the regression tests folder during development.
We should rename this file without the "1-" before opening a PR for review.
  stack build
  cd regression-tests
  ./runtests.sh -k tests/1-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-lifted tests/1-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-inlined tests/1-inlining-ex-1.ssl
  stack exec sslc -- tests/1-inlining-ex-1.ssl
*/


// print character followed by newline
putc cout_ c =
  after 1, cout_ <- c
  wait cout_
  after 1, cout_ <- 10
  wait cout_

/*
Example:  r is multiunsafe; q and w are OnceSafe, post-inline inlines r
Input:
main cin cout = 
  let r = 25
  let q = r + 25   // 50
  let w = r + q    // 75
  w

Expected Output:
main cin cout = 
  (25 + 25 + q)
  
*/

main cin cout = 
  let r = 25
  let q = r + 25   // 50
  let w = r + q    // 75
  // w
  putc cout w


  


