/*
NOTE:
This file starts with 1 so it appears at the top of the regression tests folder during development.
We should rename this file without the "1-" before opening a PR for review.
  stack build
  cd regression-tests
  ./runtests.sh -k tests/1-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-lifted tests/1-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-inlined tests/1-inlining-ex-1.ssl
  stack exec sslc -- tests/1-inlining-ex-1.ssl
*/

/* 
  TODO: make this test actually do something!

*/

// print single digit number; account for ascii offset
putd cout_ c =
  after 1, cout_ <- (c + 48)
  wait cout_

/*
Example:  r is oncesafe, q is multiunsafe; post-inline inlines q; checking operator precedence
Input:
main cin cout = 
  let q = 2
  let r = 3 + q
  putd cout (r + q - q)

Expected Output:
main cin cout = 
  let q = 2
  let r = 3 + q
  putd cout (2 + (3 + 2) * 2 - 6) 
  // I don't think the pretty printer prints parens around operators correctly right now
  
*/

main cin cout = 
  let q = 2
  let r = 3 + q
  putd cout (q + r * q - 6)