/*
NOTE:
This file starts with 1 so it appears at the top of the regression tests folder during development.
We should rename this file without the "1-" before opening a PR for review.
  stack build
  cd regression-tests
  ./runtests.sh -k tests/1-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-typed tests/1-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-lifted tests/1-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-final tests/1-inlining-ex-1.ssl
  stack exec sslc -- tests/1-inlining-ex-1.ssl
*/

/* 
  TODO: make this test actually do something!

*/

// print single digit number; account for ascii offset
putd cout c =
  after 1, cout <- (c + 48)
  wait cout


//g a b c d e f = fun arg0 {arg0 + 45}

main cin cout = 
 // let z = fun a 
 //             a + 4
 // z is equivalent \a -> a + 4
 //let q = 5
 // let r = q + 1 
  
 // w is equivalent to (\_ -> r) 2
 // let w = (fun _ { r }) 2

 // let z = (fun _ { (fun _ { r }) + r }) 2

//(fun a1 {a1 + 5}) r
  putd cout 6
