// check that optimize par pass rewrites par expressions 
// that have all instantaneous arguemnts as tuples 

type Pair2 a b
    Pair2 a b

add a b = a + b

main cin cout = 
    let q = par 2+3 // instantaneous
            	3+4 // instantaneous
                
    // ^should rewrite q as a tuple
    after 1, cout <- 5 + 48    // Should print 5
    wait cout
    after 1, cout <- 10
    wait cout
