// check that optimize par pass does NOT rewrite par expressions 
// that have at least one non-instantaneous argument

type Pair2 a b
    Pair2 a b

add a b = a + b

main cin cout = 
    let q = par add 2 3 // functions are not necessarily instantaneous
                add 3 4 // functions are not necessarily instantaneous
    // ^should NOT rewrite q as a tuple
    after 1, cout <- 5 + 48    // Should print 5
    wait cout
    after 1, cout <- 10
    wait cout
