/*
NOTE:
This file starts with the letter a so it is easy to find within the regression tests folder during development.
We should rename this file without the "a-" before opening a PR for review.
{-
  stack build
  cd regression-tests
  ./runtests.sh -k tests/a-inlining-ex-5.ssl
  stack exec sslc -- --dump-ir-typed tests/a-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-lifted tests/a-inlining-ex-1.ssl
  stack exec sslc -- tests/a-inlining-ex-5.ssl
-}


// print digit; account for ascii offset
putd cout_ c =
  after 1, cout_ <- (c + 48)
  wait cout_

main cin cout = 
  let q = 5
      r = 6
  let z = q + r
  putd cout z

  


