/*
NOTE:
This file starts with the letter a so it is easy to find within the regression tests folder during development.
We should rename this file without the "a-" before opening a PR for review.
{-
  stack build
  cd regression-tests
  ./runtests.sh -k tests/a-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-typed tests/a-inlining-ex-1.ssl
  stack exec sslc -- --dump-ir-lifted tests/a-inlining-ex-1.ssl
-}
*/


// print digit; account for ascii offset
/*
putd cout c =
  after 1, cout <- (c + 48)
  wait cout
*/

//g a b c d e f = fun arg0 {arg0 + 45}

main cin cout = 
  let z = fun a 
              a + 4
  let q = 5
  let r = q + 1 
  let w = (fun _ { r }) 2
  (fun a1 {a1 + 5}) r
  //putd cout r
