type Nullary
  False
  Leaf

type Shape 
  Rect Int Int
  Square Int    

// to check IR output, got to regression-tests directory, then do
// stack exec -- sslc --dump-ir-final tests/adt-partially-applied.ssl 

square_con sideLen : Int -> Shape = Square sideLen

perimeter (shp : Shape) -> Int = 
  match shp
   Square a = a+a+a+a
   Rect a b  = a+b+a+b

main ( cout : & Int ) -> () =
  // what a call to a constructor func should like
  let a = square_con 66
  // fully applied
  let b = Square 66                            // B
  // unapplied
  let c = Square
  //let d = Rect
  // nullary dcon (should not get changed to func app!)
  //let e = Leaf
  // partially applied
  // let d = Rect 2
  // partially applied/unapplied inside another App

  //let bb = match b 
  //          Square a = a 
  //          _ = 88
  after 10 , (cout : & Int) <- 66
  wait (cout : & Int)
