type Nullary
  False
  Leaf

type Shape 
  Rect Int Int
  Square Int    

// to check IR output, got to regression-tests directory, then do
// stack exec -- sslc --dump-ir-final tests/adt-partially-applied.ssl 

square_con sideLen : Int -> Shape = Square sideLen

perimeter (shp : Shape) -> Int = 
  match shp
   Square a = a+a+a+a
   Rect a b  = a+b+a+b

main ( cout : & Int ) -> () =

  // what a call to a constructor func should like
  let a = square_con 16

  // fully applied
  let b = Square 16   

  // unapplied
  //let c = Square                 // throws errors because closures aren't in codegen yet
  //let d = Rect                   // throws errors because closures aren't in codegen yet

  // partially applied
  //let e = Rect 2                 // throws errors because closures aren't in codegen yet

  // nullary dcon (should not get changed to func app!)
  let f = Leaf

  after 10 , (cout : & Int) <- perimeter a + 2
  wait (cout : & Int)
