ms t = 1000000 * t

blink n period led =
  let n_ = new n
  let event = new ()
  while deref n_ > 0
    led <- 1 - deref led
    after period, event <- ()
    wait event
    n_ <- deref n_ - 1

main cin cout =
  let putc c =
       after 1, cout <- c
       wait cout
  let display led =
       loop
         wait led
         putc (deref led + 48)
	 putc 10
  let led = new 0
  par blink 12 (ms 50) led
      blink 20 (ms 30) led
      display led
  
