ms t = 1000000 * t

blink n period led =
  let n_ = new n
  let event = new ()
  while deref n_ > 0
    led <- 1 - deref led
    after period, event <- ()
    wait event
    n_ <- deref n_ - 1

main cin cout =
  let putc c =
       after 1, cout <- c
       wait cout
  let display kill led =
       wait led
            kill
       while deref kill == 0
         putc (deref led + 48)
         putc 10
         wait led
              kill
  let led = new 0
  let kill = new 0
  let blinkers _ =
        par blink 12 (ms 50) led
            blink 20 (ms 30) led
        kill <- 1
  par blinkers ()
      display kill led
