ms t = 1000000 * t

blink n putc period led =
  let toggle led = led <- 1 - deref led
  let n_ = new n
  let event = new ()
  while deref n_ > 0
    putc 33
    toggle led
    after period, event <- ()
    wait event
    n_ <- deref n_ - 1

main cin cout =
  let putc c =
       after 1, cout <- c
       wait cout
  let display led =
       loop
         wait led
         putc (deref led + 48)
	 putc 10
  let led = new 0
  par blink 10 putc (ms 500) led
      blink 10 putc (ms 300) led
      display led
/*  
  par blink 10 putc (ms 500) led
      blink 10 putc (ms 300) led
      blink 10 putc (ms 200) led
      display led
      */
  
