clear (cout : & Int) -> () =
    after 500 , (cout : & Int) <- 7    // clear with "\033[2J" (see -main.c for details)
    wait (cout : & Int)
    after 5 , (cout : & Int) <- 13     // carriage return
    wait (cout : & Int)

print (cout : & Int) (c : Int) -> () =
    after 10 , (cout : & Int) <- c  
    wait (cout : & Int)

//let num = 0
// 45 47 92 124
// -  /   \  |
// \ | / - \ | / - \
// match x / 50

main ( cout : & Int ) (num : & Int) -> () =
    after 10, (num : & Int) <- 0
    wait num
  //  loop
    let x = 5
    
    
    after 10, cout <- match (num)
                             cout = 93
                             _ = 94
   // after 10, (cout : & Int) <- h    // '\'
    wait (cout : & Int)
        

        






        