// Compiler never terminates!

gcd a b cout =
  after 1, cout <- a + 48
  wait cout
  after 1, cout <- 32
  wait cout
  after 1, cout <- b + 48
  wait cout
  after 1, cout <- 10
  wait cout
  if a == b
    a
  else
    if a < b
      after 1, cout <- 60 // <
      wait cout
      gcd a (b - a)
    else
      after 1, cout <- 62 // >
      wait cout
      gcd (a - b) b

main cin cout =
  let c = gcd 8 9 cout
  after 1, cout <- c + 48
  wait cout
  after 1, cout <- 10
  wait cout
