type String
  Cons Int String
  Nil

putc_ (cout : &Int) d =
  after 1, cout <- d
  wait cout

puts_ putc s =
  let puts__ ss =
        match ss
          Cons c s = putc c
                     puts__ s
          Nil = ()
  puts__ s

main cin cout =
  let putc = putc_ cout
  let puts = puts_ putc
  let hello = Cons 72 (Cons 101 (Cons 108 (Cons 108
               (Cons 111 (Cons 49 (Cons 51 (Cons 10 Nil)))))))
  puts hello
