// testing that match arm is eliminated

type List
  Cons Int List
  Nil

type Color
  RGB Int Int
  Red
  Black

// print single digit number; account for ascii offset
putd cout_ c =
  after 1, cout_ <- (c + 48)
  wait cout_

main cin cout = 
   let test = Cons 4 (Cons 3 (Cons 9 Nil))
   match test
       Cons 4 (Cons 3 (Cons x y)) = putd cout 4 
       Cons _ g = putd cout 7
       _ = putd cout 6

// should reduce to putd cout 4 

/*
main (cin : _t47) (cout : (& Int32)) -> () = 
  let __pat_anon0 = 4
  let __pat_anon1 = Cons 3 (Cons 9 (Nil))
  match __pat_anon0
    4 = match __pat_anon1
          Cons __pat_anon2 __pat_anon3 = match __pat_anon2
                                           3 = match __pat_anon3
                                                 Cons __pat_anon4 __pat_anon5 = putd cout 4
                                                 Nil  = let g = __pat_anon1
                                                        putd cout 7
                                           _ = let g = __pat_anon1
                                               putd cout 7
          Nil  = let g = __pat_anon1
                 putd cout 7
    _ = let g = __pat_anon1
        putd cout 7
*/

/*
main (cin : _t47) (cout : (& Int32)) -> () = 
  let __pat_anon1 = Cons 3 (Cons 9 (Nil))
  match __pat_anon1
    Cons __pat_anon2 __pat_anon3 = match __pat_anon2
                                     3 = match __pat_anon3
                                           Cons __pat_anon4 __pat_anon5 = putd cout 4
                                           Nil  = let g = __pat_anon1
                                                  putd cout 7
                                     _ = let g = __pat_anon1
                                         putd cout 7
    Nil  = let g = __pat_anon1
           putd cout 7
*/