// testing that match arm is eliminated
// checking nested patterns in arms

type List
  Cons Int List
  Nil

type Color
  RGB Int Int
  Red
  Black

// print single digit number; account for ascii offset
putd cout_ c =
  after 1, cout_ <- (c + 48)
  wait cout_

main cin cout = 
  match (Cons 4 (Cons 3 Nil))
   Cons 4 (Cons 3 Nil) = putd cout 4 
   Cons _ g = putd cout 7
   _ = putd cout 6

// should reduce to putd cout 4 