putip_ putc x =
  if x < 10
    putc (x + 48)
  else
    putip_ putc (x / 10)
    putc (48 + x % 10)

puti_ putc x =
  if x < 0
    putc 45 // -
    putip_ putc (0 - x)
  else
    putip_ putc x

type Maybe a
  Just a
  Nothing

type List a
  Cons a (List a)
  Nil

// Print the elements of an integer-valued list
printl_ puti putc l =
  match l
    Cons v ll = puti v
                putc 32 // sp
                printl_ puti putc ll
    Nil = putc 10 // nl


// OCaml-style List library begins
//
// See /usr/lib/ocaml/list.ml

length_aux len l =
  match l
    Cons _ ll = length_aux (len + 1) ll
    Nil     = len

length l = length_aux 0 l

hd l = match l
         Cons v _ = Just v
         Nil    = Nothing

tl l = match l
        Cons _ ll = Just ll
        Nil     = Nothing

nth_aux l n =
  match l
    Nil       = Nothing
    Cons c ll = if n == 0
    	          Just c
	        else
	          nth_aux ll (n-1)

nth l n = if n < 0 { Nothing } else { nth_aux l n }


// Test the various functions

main cin cout =
  let putc c =
       after 1, cout <- c
       wait cout
  let putnl _ = putc 10
  let puti = puti_ putc
  let printl l = printl_ puti putc l
  
  let zero = Nil
  let one = Cons 57 Nil
  let two = Cons 21 one
  let three = Cons 42 (Cons 17 (Cons 8 Nil))

  putc 65 // A
  putc 10 // nl  
  printl one   // 57
  printl two   // 21 57
  printl three  // 42 17 8
  puti (length zero) // 0
  putnl ()
  puti (length one)  // 1
  putnl ()
  puti (length two)  // 2
  putnl ()
  puti (length three)  // 3
  putnl ()
  
  puti (match (hd three)
         Just i  = i     // 42
         Nothing = 0)
  putnl ()
  match (tl three)
   Just l =
     match l
         Just ll = puti ll // 17
         Nothing = putc 68
   Nothing = putc 66
  putnl ()

  printl (match (tl three)
           Just l  = l       // 17 8
           Nothing = Nil)

  match (nth three 0)
    Just i = puti i    // 42
    Nothing = putc 66
  putnl ()

  match (nth three 1)
    Just i = puti i    // 17
    Nothing = putc 66
  putnl ()

  match (nth three 2)
    Just i = puti i    // 8
    Nothing = putc 66
  putnl ()

  match (nth three 3)
    Just i = putc 33
    Nothing = putc 45 // -
  putnl ()

  match (nth three 4)
    Just i = putc 33
    Nothing = putc 45 // -
  putnl ()

  match (nth three (0 - 1)) // FIXME: might be nice to have "-3" work
    Just i = putc 33
    Nothing = putc 45 // -
  putnl ()


