// ./runtests.sh tests/list4.ssl
// stack exec sslc -- --dump-ir tests/list4.ssl
// stack exec sslc -- tests/list4.ssl



type List a
  Cons a (List a)
  Nil

main cin cout =
  let putc c = after 1, cout <- c
               wait cout
  let printNil _ = putc '['   // do we not have 0 argument functions??
                   putc ']'

  // want to add syntax for list here!
  let two = Cons 65 (Cons 68 Nil) // 'A' : 'D' : []
  //^ instead of this, eventually want to be able to do
  //^ let two = ['A', 'D']
  
  match two
    Cons c _ = putc c  // Should print A
    Nil      = printNil 33
  putc '\n'

  match two
    Cons _ l = match l
                 Cons c _ = putc c   // Should print D
		 Nil      = printNil 33
    Nil      = printNil 33
  putc '\n'

  match two
    Cons _ l = match l
                 Cons _ l = match l
                             Cons c _ = putc 33 // should never reach here
                             Nil      = printNil 33
		 Nil      = printNil 33
    Nil      = printNil 33
  putc '\n'
