putc (cout : &Int) c =
  after 1, cout <- c
  wait cout

main cin (cout : &Int) =
   let f a b =  if a > 1
                    g (a / b) (b / 2)
                else
                    h (a / 2)
       g a b =  if a > 1
                    h (b / 2)
                else
                    f (a / b) (b / 2)
       h a   =  if a > 1
                    f a (a / 2)
                else
                    a / 2

   putc cout (f 64 32 + 48)
   putc cout 10
   putc cout (g 64 32 + 48)
   putc cout 10
