// checking that 2-tuples can be declared with new syntax
type Pair2 a b
    Pair2 a b

add a b = a + b

printCharTuple putc p =
  match p
   (x,y) = putc x
           putc 32
           putc y

main cin cout =
    let putc c = after 1, cout <- c
                 wait cout
    let putnl _ = putc 10
   
    let x = 66
    let y = 67
    let q = par add x 0
                add y 0
    let q =(add x 0, add y 0)
    let r = (x,y)
    printCharTuple putc r // this is okay
    putnl ()
    //printCharTuple putc q // this causes type error
    putnl ()

/*
###### Testing par-tuple
stack exec sslc -- tests/par-tuple.ssl > out/par-tuple.c
TypeError (ErrorMsg "Ill-typed expression. Expected Type Pair2 [Type Int32 [],Type Int32 []], but got Type (,) [Type Int32 [],Type Int32 []]")
###### FAILED
*/