type Tree
  TwoChildren Tree Tree
  OneChild Int Tree
  Leaf

type MyBool 
  MyTrue Int
  MyFalse Int Int

main ( cout : & Int ) -> () =
  let b = (MyTrue 999)
  let c = (MyFalse 949 38) 
  let d = Leaf 
  let e = OneChild 777 Leaf
  let a = match d
            Leaf = 78
            OneChild a' a'' = 0
            TwoChildren b' b'' = 0
  // let f = OneChild 888 e //doesn't work yet
  after 10 , (cout : & Int) <- a