// tests whether a 2-tuple(Pair) can be implemented in Ssland with ADTs
// without builtin syntax

type Pair2 a b
    Pair2 a b

putip_ putc x =
  if x < 10
    putc (x + 48)
  else
    putip_ putc (x / 10)
    putc (48 + x % 10)

puti_ putc x =
  if x < 0
    putc 45 // -
    putip_ putc (0 - x)
  else
    putip_ putc x

// tests the pattern match of pairs
printl_ puti putc p =
  match p
    Pair2 x y = puti x
                putc 32
                puti y


main cin cout =
    let putc c = after 1, cout <- c
                 wait cout
    let puti = puti_ putc
    let putnl _ = putc 10
    let printl l = printl_ puti putc l


    let x_ = Pair2 1 2
    let y_ = Pair2 3 4

    printl x_
    putnl ()
    printl y_
