putip_ putc x =
  if x < 10
    putc (x + 48)
  else
    putip_ putc (x / 10)
    putc (48 + x % 10)

puti_ putc x =
  if x < 0
    putc 45 // -
    putip_ putc (0 - x)
  else
    putip_ putc x

// test match nested tuples ((x,y),z)
print_nested puti putc tuptup = 
    match tuptup 
      ((x,y),z) = puti x
                  putc 32
                  puti y
                  putc 32
                  puti z

main cin cout = 
    let putc c = after 1, cout <- c
                 wait cout
    let puti = puti_ putc
    let putnl _ = putc 10
    let print_nest l = print_nested puti putc l
    let s = ((4,5),6)

    print_nest s


