name:                sslang
version:             0.1.0.0
github:              "sedwards-lab/sslang"
license:             BSD3
author:              "Stephen A. Edwards"
maintainer:          "sedwards@cs.columbia.edu"
copyright:           "2021 Stephen A. Edwards"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/sedwards-lab/sslang#README>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - prettyprinter >= 1.7.0
  - array
  - mtl
  - containers
  - language-c-quote
  - mainland-pretty
  - srcloc
  - composition
  - comonad

executables:
  sslc:
    main:                Main.hs
    source-dirs:         app

    ghc-options:
    - -Wall
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N

    dependencies:
    - sslang
    - prettyprinter >= 1.7.0

    build-tools:
    - happy
    - alex

_test-suite: &test-suite
  main: Spec.hs
  dependencies:
  - sslang
  - hspec
  - here
  - template-haskell
  - containers
  - comonad

tests:
  regression:
    main: test/regression/Spec.hs
    dependencies:
    - process

  scanner:
    <<: *test-suite
    source-dirs:
    - test/lib
    - test/scanner

  parser:
    <<: *test-suite
    source-dirs:
    - test/lib
    - test/parser

  prettyprinter:
    <<: *test-suite
    source-dirs:
    - test/lib
    - test/prettyprinter

  typeinference:
    <<: *test-suite
    source-dirs:
    - test/lib
    - test/typeinference

  ir:
    <<: *test-suite
    source-dirs:
    - test/lib
    - test/ir
