#!/bin/sh

Report () {
    echo ""
    echo $*
    eval "./build/$*"
}

echo "Running examples"

if [ ! -f build/fib ]
then
    echo "build/fib not found.  Did you \"make examples\"?"
    exit 1
fi

echo ""
echo "Recursive single-instant Fibonacci"
Report fib
Report fib 4
Report fib 5
Report fib 13
Report fib 15

echo ""
echo "Recursive single-instant parallel Fibonacci"
Report fib2
Report fib2 4
Report fib2 5
Report fib2 13
Report fib2 15

echo ""
echo "Recursive parallel Fibonacci with delays"
Report fib3
Report fib3 4
Report fib3 5
Report fib3 13
Report fib3 15

echo ""
echo "Demonstrate deterministic concurrency"
Report onetwo

echo ""
echo "Count the events on seconds"
Report clock

echo ""
echo "Simulate a clocked digital circuit with two adders and two registers"
echo "q1 should add q2+1 to itself each time; q2 should increment"
Report counter

echo ""
echo "Simulate a similar circuit, but with a different clock generator"
Report counter2







