name: "Setup cached build environment with cabal"
description: "Setup the build using cache"
inputs:
  os:
    description: "Operating system: Linux, Windows or macOS"
    required: true
  resolver:
    description: "Stack resolver"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Ubuntu dependencies
      if: ${{ inputs.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc valgrind clang

    - name: Setup cabal
      uses: haskell/actions/setup@v1.2
      with:
        ghc-version: ${{ input.ghc }}
        cabal-version: ${{ input.cabal }}

    - name: Cabal update and freeze
      run:
        cabal v2-update
        cabal v2-freeze

    - name: Cache .cabal/store and dist-newstyle
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ input.os }}-${{ input.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ input.os }}-${{ input.ghc }}-

    - name: Build
      run: |
        cabal v2-build


