[env]
framework = zephyr
lib_deps =
  https://github.com/ssm-lang/ssm-runtime.git

[env:nrf52840_dk]
platform = nordicnrf52
board = nrf52840_dk
build_flags = -DSSM_SECOND=16000000L -Wno-parentheses
monitor_speed = 115200

[env:disco_f407vg]
platform = ststm32
board = disco_f407vg
build_flags = -DSSM_SECOND=84000000L -Wno-parentheses
monitor_speed = 115200
