name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - 'src/**'

jobs:
  doc-build-html:
    name: "Build and Deploy Haddock documentation"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-build
      with:
        os: ubuntu-latest
        resolver: lts-18.6

    - name: Build documentation
      run: |
        stack haddock --no-haddock-deps

    - name: Deploy documentation
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./haddock-out
        publish_branch: gh-pages
