name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build and test sslang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        resolver: [lts-18.6]
        ghc: ["8.10.7"]
        cabal: ["3.6.2"]

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-build
      with:
        os:  ${{ matrix.os }}
        resolver: ${{ matrix.resolver }}
        ghc: ${{ matrix.ghc }}
        cabal: ${{ matrix.cabal }}

    - name: Run sslang test suite
      run: |
        cabal test
