name: Tester

on:
  push:
    paths:
      - '.github/**'
      - 'app/**'
      - 'lib/**'
      - 'regression-tests/**'
      - 'src/**'
      - 'test/**'
      - 'unit-tests/**'
  pull_request:
    paths:
      - '.github/**'
      - 'app/**'
      - 'lib/**'
      - 'regression-tests/**'
      - 'src/**'
      - 'test/**'
      - 'unit-tests/**'

jobs:
  test:
    name: Build and test sslang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        resolver: [lts-18.6]
    env:
      ARGS: "--stack-yaml stack.yaml --no-terminal --system-ghc"

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install Haskell Stack
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-version: latest

    - name: Setup Haskell Stack
      run: |
        stack setup --resolver ${{ matrix.resolver }}

    - name: Cache ~/.stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.resolver }}-haskell-${{ hashFiles('stack.yaml') }}-stack

    - name: Install dependencies
      run: |
        stack build ${ARGS} --only-dependencies

    - name: Build
      run: |
        stack build ${ARGS}

    - name: Test
      run: |
        stack test --stack-yaml stack.yaml
