name: Test

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'package.yaml'
      - 'stack.yaml'
      - 'stack.yaml.lock'
      - 'app/**'
      - 'lib/**'
      - 'regression-tests/**'
      - 'src/**'
      - 'test/**'
      - 'unit-tests/**'
  pull_request:
    paths:
      - '.github/**'
      - '*.yml'
      - 'app/**'
      - 'lib/**'
      - 'regression-tests/**'
      - 'src/**'
      - 'test/**'
      - 'unit-tests/**'

jobs:
  test:
    name: Build and test sslang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        resolver: [lts-18.6]

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-build
      with:
        os:  ${{ matrix.os }}
        resolver: ${{ matrix.resolver }}

    - name: Build sslang compiler
      run: |
        stack build

    - name: Run sslang test suite
      run: |
        stack test --stack-yaml stack.yaml
